templateVersion: 1.0.0
defaultVersion: '1.18'
documentation: https://docs.gitea.io
type: gitea
name: Gitea
description: Gitea is a community managed lightweight code hosting solution written in Go.
labels:
  - storage
  - git
services:
  $$id:
    name: Gitea
    documentation: https://docs.gitea.io
    image: gitea/gitea:$$core_version
    volumes:
      - $$id-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DOMAIN=$$config_domain
      - SSH_DOMAIN=$$config_ssh_domain
      - ROOT_URL=$$config_root_url
      - SECRET_KEY=$$secret_secret_key
      - INTERNAL_TOKEN=$$secret_internal_token
      - SSH_PORT=22
      - START_SSH_SERVER=$$config_start_ssh_server
    ports:
      - '3000'
      - '22'
    proxy:
      - port: '22'
        hostPort: $$config_hostport_ssh
variables:
  - id: $$config_hostport_ssh
    name: SSH_PORT
    label: SSH Port
    defaultValue: '8022'
    description: ''
    required: true
  - id: $$config_domain
    name: DOMAIN
    label: Domain
    defaultValue: $$generate_domain
    description: ''
  - id: $$config_ssh_domain
    name: SSH_DOMAIN
    label: SSH Domain
    defaultValue: $$generate_domain
    description: ''
  - id: $$config_start_ssh_server
    name: START_SSH_SERVER
    label: Start SSH Server
    defaultValue: 'true'
    description: ''
  - id: $$config_root_url
    name: ROOT_URL
    label: Root URL of Gitea
    defaultValue: $$generate_fqdn_slash
    description: ''
  - id: $$secret_secret_key
    name: SECRET_KEY
    label: Secret Key
    defaultValue: $$generate_hex(32)
    description: ''
  - id: $$secret_internal_token
    name: INTERNAL_TOKEN
    label: Internal JWT Token
    defaultValue: $$generate_token
    description: ''
