templateVersion: 1.0.0
defaultVersion: v2.16.1
documentation: https://hasura.io/docs/latest/index/
type: hasura
name: Hasura
description: Instant realtime GraphQL APIs on any Postgres application, existing or new.
labels:
  - graphql
  - database
services:
  $$id:
    name: Hasura
    depends_on:
      - $$id-postgresql
    image: hasura/graphql-engine:$$core_version
    volumes: []
    environment:
      - HASURA_GRAPHQL_ENABLE_CONSOLE=$$config_hasura_graphql_enable_console
      - >-
        HASURA_GRAPHQL_METADATA_DATABASE_URL=$$secret_hasura_graphql_metadata_database_url
      - HASURA_GRAPHQL_ADMIN_SECRET=$$secret_hasura_graphql_admin_secret
    ports:
      - '8080'
  $$id-postgresql:
    name: PostgreSQL
    depends_on: []
    image: postgres:12-alpine
    volumes:
      - $$id-postgresql-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=$$config_postgres_user
      - POSTGRES_PASSWORD=$$secret_postgres_password
      - POSTGRES_DB=$$config_postgres_db
    ports: []
variables:
  - id: $$config_hasura_graphql_enable_console
    name: HASURA_GRAPHQL_ENABLE_CONSOLE
    label: Enable Hasura Console
    defaultValue: 'true'
    description: ''
  - id: $$secret_hasura_graphql_metadata_database_url
    name: HASURA_GRAPHQL_METADATA_DATABASE_URL
    label: Hasura Metadata Database URL
    defaultValue: >-
      postgresql://$$config_postgres_user:$$secret_postgres_password@$$id-postgresql:5432/$$config_postgres_db
    description: ''
  - id: $$secret_hasura_graphql_admin_secret
    name: HASURA_GRAPHQL_ADMIN_SECRET
    label: Hasura Admin Password
    defaultValue: $$generate_password
    description: ''
    showOnConfiguration: true
  - id: $$config_postgres_user
    name: POSTGRES_USER
    label: PostgreSQL User
    defaultValue: $$generate_username
    description: ''
  - id: $$secret_postgres_password
    name: POSTGRES_PASSWORD
    label: PostgreSQL Password
    defaultValue: $$generate_password
    description: ''
  - id: $$config_postgres_db
    name: POSTGRES_DB
    label: PostgreSQL Database
    defaultValue: hasura
    description: ''
