templateVersion: 1.0.0
defaultVersion: 0.101.2
documentation: https://docs.nocodb.com
type: nocodb
name: NocoDB
description: >-
  Turns any MySQL, PostgreSQL, SQL Server, SQLite & MariaDB into a
  smart-spreadsheet.
labels:
  - database
  - airtable
  - spreadsheet
services:
  $$id:
    name: NocoDB
    image: nocodb/nocodb:$$core_version
    environment:
      - PORT=$$config_port
      - NC_DB=$$config_nc_db
      - DATABASE_URL=$$secret_database_url
      - NC_PUBLIC_URL=$$config_public_url
      - NC_AUTH_JWT_SECRET=$$secret_auth_jwt_secret
      - NC_SENTRY_DSN=$$secret_sentry_dsn
      - >-
        NC_CONNECT_TO_EXTERNAL_DB_DISABLED=$$config_connect_to_external_db_disabled
      - NC_DISABLE_TELE=$$config_disable_tele
    volumes:
      - $$id-data:/usr/app/data
    ports:
      - '8080'
variables:
  - id: $$config_nc_db
    name: NC_DB
    label: Database
    defaultValue: ''
    description: >-
      MySQL, PostgreSQL and MSSQL connection urls supported. If absent: A local
      SQLite will be created in root folder.
  - id: $$config_port
    name: PORT
    label: Port
    defaultValue: '8080'
    description: ''
  - id: $$secret_database_url
    name: DATABASE_URL
    label: Database URL
    defaultValue: ''
    description: >-
      JDBC URL Format. Can be used instead of NC_DB. Used in 1-Click Heroku
      deployment.
  - id: $$config_public_url
    name: NC_PUBLIC_URL
    label: Public URL
    defaultValue: ''
    description: >-
      Used for sending Email invitations. If absent: Best guess from http
      request params.
  - id: $$secret_auth_jwt_secret
    name: NC_AUTH_JWT_SECRET
    label: Auth JWT Secret
    defaultValue: $$generate_hex(64)
    description: >-
      JWT secret used for auth and storing other secrets. If absent: A Random
      secret will be generated.
  - id: $$secret_sentry_dsn
    name: NC_SENTRY_DSN
    label: Sentry DSN
    defaultValue: ''
    description: For Sentry monitoring.
  - id: $$config_connect_to_external_db_disabled
    name: NC_CONNECT_TO_EXTERNAL_DB_DISABLED
    label: Disable External Database
    defaultValue: '0'
    description: Disable Project creation with external database. (Enter "1" to disable).
  - id: $$config_disable_tele
    name: NC_DISABLE_TELE
    label: NocoDB Disable Telemetry
    defaultValue: '1'
    description: Disable telemetry (Enter "1" to disable).
