templateVersion: 1.0.0
defaultVersion: 2023.01.15-52d41559
documentation: https://docs.searxng.org/
type: searxng
name: SearXNG
description: >-
  Free internet metasearch engine which aggregates results from more than 70
  search services.
services:
  $$id:
    name: SearXNG
    depends_on:
      - $$id-redis
    image: searxng/searxng:$$core_version
    volumes:
      - $$id-searxng:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=$$config_searxng_base_url
    ports:
      - '8080'
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    files:
      - location: /etc/searxng/settings.yml
        content: |2-

                                        # see https://docs.searxng.org/admin/engines/settings.html#use-default-settings
                                        use_default_settings: true
                                        server:
                                          secret_key: $$secret_secret_key
                                          limiter: true
                                          image_proxy: true
                                        ui:
                                          static_use_hash: true
                                        redis:
                                          url: redis://:$$secret_redis_password@$$id-redis:6379/0
  $$id-redis:
    name: Redis
    command: >-
      redis-server --requirepass $$secret_redis_password --save "" --appendonly
      "no"
    depends_on: []
    image: redis:7-alpine
    volumes:
      - $$id-redis-data:/data
    environment:
      - REDIS_PASSWORD=$$secret_redis_password
    ports: []
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
variables:
  - id: $$config_searxng_base_url
    name: SEARXNG_BASE_URL
    label: SearXNG Base URL
    defaultValue: $$generate_fqdn
    description: ''
  - id: $$secret_secret_key
    name: SECRET_KEY
    label: Secret Key
    defaultValue: $$generate_hex(64)
    description: ''
  - id: $$secret_redis_password
    name: REDIS_PASSWORD
    label: Redis Password
    defaultValue: $$generate_password
    description: ''
