templateVersion: 1.0.0
defaultVersion: 1.19.4
documentation: https://hub.docker.com/r/louislam/uptime-kuma
description: A free & fancy self-hosted monitoring tool.
labels:
  - uptime
type: uptimekuma
name: UptimeKuma
services:
  $$id:
    image: louislam/uptime-kuma:$$core_version
    environment: []
    volumes:
      - $$id-uptimekuma:/app/data
    ports:
      - '3001'
variables: []
