templateVersion: 1.0.0
defaultVersion: 0.8.0
documentation: https://github.com/benbusby/whoogle-search
type: whoogle
name: Whoogle Search
description: A self-hosted, ad-free, privacy-respecting metasearch engine
labels:
  - search
  - google
services:
  $$id:
    name: Whoogle Search
    documentation: https://github.com/benbusby/whoogle-search
    depends_on: []
    image: benbusby/whoogle-search:$$core_version
    cap_drop:
      - ALL
    environment:
      - WHOOGLE_USER=$$config_whoogle_username
      - WHOOGLE_PASS=$$secret_whoogle_password
      - WHOOGLE_CONFIG_PREFERENCES_KEY=$$secret_whoogle_preferences_key
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - '5000'
variables:
  - id: $$config_whoogle_username
    name: WHOOGLE_USER
    label: Whoogle User
    defaultValue: $$generate_username
    description: Username to log into Whoogle
  - id: $$secret_whoogle_password
    name: WHOOGLE_PASSWORD
    label: Whoogle Password
    defaultValue: $$generate_password
    description: Password to log into Whoogle
    showOnConfiguration: true
  - id: $$secret_whoogle_preferences_key
    name: WHOOGLE_CONFIG_PREFERENCES_KEY
    label: Whoogle preferences key
    defaultValue: $$generate_password
    description: password to encrypt preferences
